### ISSUE TITLE
Wrong quotes in the example

### ISSUE THREAD

**Issue by lgorenstein** [tunel-apps/tunel#30]
https://github.com/tunel-apps/tunel/blob/f37899bae81e4cca83968c6282d608c6b934a09f/docs/getting_started/user-guide.rst#L345

Arguably, attempts to execute $HOME are pretty futile :) so these probably need to be single quotes rather than backticks: `echo '$HOME'`

**Comment by vsoch** [comment]
Thank you! I think this was likely a typo when writing the early docs, as when I am testing locally I definitely do:

```bash
$ tunel exec osg echo '$HOME'
ssh osg echo $HOME
 /home/sochat1
```
with single quotes! And just made the tweak so it will be live with the docs shortly. https://github.com/tunel-apps/tunel/commit/0e9151e654a5ee09bcedb9705d8fec3d31026e3c. Thank you for catching this!
